#!/usr/bin/env bash

target_ip=$1
rsync -avz \
    --exclude "__pycache__" \
    --exclude ".git" \
    \
    --exclude "build" \
    --exclude "install" \
    --exclude "log" \
    \
    --exclude "runs" \
    --exclude "yolo26n.pt" \
    \
    --include "resource/weights-best" \
    --include "resource/datasets" \
    --exclude "resource/datasets/lane-detection/legacy" \
    --include "resource/libs" \
    --exclude "resource/*" \
    \
    --exclude "src/watermelon_robot/resource/model_weights" \
    $HOME/repository/watermelon-robot wheeltec@$target_ip:~/fr_ws

rsync -avz \
    $HOME/repository/watermelon-robot/resource/resource/ wheeltec@$target_ip:~/fr_ws/watermelon-robot/src/watermelon_robot/resource/