########################################### 以下是通用配置 ##########################################
# 目标检测模型相关
target_detection:
  model: 
    name: "yolov26-best-fp16.engine"
    task: "target-detection"
    use_engine: True
    device_no: "0"
    use_half: True
    image_size: [480, 640]
    confidence: 0.4
    iou: 0.8

# -------------------------------------------------------
# 导航线检测相关
lane_detection: 
  model:  
    name: "yolo26n-seg-b64-1779873368-fp16.engine"
    task: "lane-detection"
    use_engine: True
    device_no: "0"
    use_half: True
    confidence: 0.8
  roi:
    y_min_portion: 0.75                                     # 兴趣区域上界占图片高度比例
    y_max_portion: 0.99                                     # 兴趣区域下界占图片高度比例
  detect_step: 10
  lane_offset: 10
  
# -------------------------------------------------------
# 机械臂配置相关
robotic_arm: 
  activate: "fr3_0"
  profiles:
    fr3_0:
      ip: "192.168.58.2"
      speed_rate: 20                                            # 机械臂运动速率
      standby_status:
        use_cartesian: False                                    # 选择是否使用笛卡尔六元组表述机械臂初始姿态，若为 False 则使用关节空间描述
        status: [90.0, -120.0, 120, -180, -90, -90]
      stand_by_joint_space: []
      calibration_marix: [[0, -1, 0, 25],                       # 相机手眼校准矩阵。在“眼在手上”方案中应为相机参考系到末端执行器变换矩阵；在“眼在手外”方案中应为相机参考系到机械臂世界坐标系变换矩阵。
                          [1, 0, 0, 60],
                          [0, 0, 1, 10],
                          [0, 0, 0, 1]]
      tool_error: [-50, 170, -90]                               # 剪刀的位置偏差（相机参考系下）
      eye_in_hand: True

    fr5_0:
      ip: "192.168.58.2"
      speed_rate: 20
      standby_status:
        use_cartesian: True
        status: [102, -282.5, 418, 180, -90, -90]
      calibration_marix: [[0, -1, 0, 25],
                          [1, 0, 0, 60],
                          [0, 0, 1, 10],
                          [0, 0, 0, 1]]
      tool_error: [0, 50, -50]
      eye_in_hand: True

# -------------------------------------------------------
# 底盘控制相关
chassis: 
  pid_controller: 
    pid_triple: [0.2, 0.02, 0.01]
    control_interval: 0.1
    integral_limit: 10
    output_limit: 10
  forward_speed: 0.65                                       # 底盘前进速度（m/s)。实验室环境设置0.4，田间设置0.6-0.7。
  stop_delay_sec: 3                                         # 当前版本底盘停止方案用来控制底盘停止的延迟。相关函数注释里有说明。

# -------------------------------------------------------
# 剪刀控制相关
scissors:
  tool_id: 8                # 剪刀在机械臂中的工具编号
  close_flag: 1             # 0/1 哪一个控制剪刀闭合
  open_delay_sec: 2         # 剪刀张开、闭合结束等待时间

# -------------------------------------------------------
# WebUI 相关


######################################## 以下是节点初始化器配置 ########################################
_node_initializer:

  ################
  # 上逻辑控制器 #
  ################
  CELESTIAL_FULCRUM:

    # 标准通信接口配置块 ###################
    ##################
    input_0: "t/target_detector/prediction/target_list"
    duplex_0: "s/robotic_arm/command"                       # 双工：机械臂控制
    duplex_1: "s/logic_controller/command"                  # 双工：上/下逻辑控制器

# -------------------------------------------------------
  
  ###############
  # 机械臂控制器 #
  ###############
  CAERULA_ARBOR:

    # 标准通信接口配置块 ###################
    ##################
    duplex_0: "s/robotic_arm/command"                   # 双工：机械臂控制

# -------------------------------------------------------

  ##################################
  # 机械臂手眼 RealSense 相机控制器 #
  ##################################
  PRESERVATOR:

    # 标准通信接口配置块 ###################
    ##################
    output_0: "t/realsense/robotic_arm/in_hand/color"      
    output_1: "t/realsense/robotic_arm/in_hand/depth"      
    output_2: "t/realsense/robotic_arm/in_hand/intrinsics" 

    # 通用配置块 ###################
    ###########
    fps: 30                                                 # 画面采集帧率

# -------------------------------------------------------

  ##############
  # 目标检测器 #
  ##############
  LYNCHPIN:

    # 标准通信接口配置块 ###################
    ##################
    input_0: "t/realsense/robotic_arm/in_hand/color"          # 输入：
    input_1: "t/realsense/robotic_arm/in_hand/depth"          # 输入：
    input_2: "t/realsense/robotic_arm/in_hand/intrinsics"     # 输入：
    output_0: "t/target_detector/prediction/target_list"      # 输出：目标队列
    output_1: "t/target_detector/visualization/overlay"       # 输出：手眼相机目标框叠加层

    # 通用配置块 ###################
    ###########
    ats:
      queue_size: 10
      slop: 0.05

# -------------------------------------------------------
  ################
  # 下逻辑控制器 #
  ################
  ORACLE:

    # 标准通信接口配置块 ###################
    ##################
    input_0: "t/lane_detector/prediction/lane_error"        # 输入：航线偏离
    output_0: "t/chassis/control_sequence"                  # 输入：航线偏离
    duplex_0: "s/logic_controller/command"                  # 双工：上/下逻辑控制器

    # 通用配置块 ###################
    ###########
    heartbeat_period_sec: 0.01                              # Heartbeat 循环周期

# -------------------------------------------------------
  
  #############
  # 底盘控制器 #
  #############
  DWDB_221E:

    # 标准通信接口配置块 ###################
    ##################
    input_0: "t/chassis/control_sequence"                   # 底盘方向控制
    output_0: "cmd_vel"                                     # 轮趣 SDK：底盘控制信号

# -------------------------------------------------------
  
  ################################
  # 底盘前视 RealSense 相机控制器 #
  ################################
  AMA_10:

    # 标准通信接口配置块 ###################
    ##################
    output_0: "t/realsense/chassis/front_facing/color"            # 输出：    
    output_1: "t/realsense/chassis/front_facing/depth"            # 输出： 
    output_2: "t/realsense/chassis/front_facing/intrinsics"       # 输出： 

    # 通用配置块 ###################
    ###########
    fps: 30           # 画面采集帧率

# -------------------------------------------------------
  
  #############
  # 航线检测器 #
  #############
  LONETRAIL:

    # 标准通信接口配置块 ###################
    ##################
    input_0: "t/realsense/chassis/front_facing/color"     
    output_0: "t/lane_detector/prediction/lane_error"         # 输出：航线偏离
    output_1: "t/lane_detector/visualization/overlay"         # 输出：底盘相机预测轨迹叠加层

    # 通用配置块 ###################
    ###########
    ats:
      queue_size: 10
      slop: 0.05

# -------------------------------------------------------

  ################
  # Sub 测试辅助节点 #
  ################
  YAN:

    # 标准通信接口配置块 ###################
    ##################
    output_0: "t/realsense/chassis/front_facing/color" 

    # 通用配置块 ###################
    ###########
    fps: 30           # 画面采集帧率
    video_path: "/home/lynchpin/repository/watermelon-robot/resource/datasets/lane-detection/legacy/video-7.mp4"

# -------------------------------------------------------

  ###############
  # Web UI 节点 #
  ###############
  PRIESTESS_EYES:

    # 标准通信接口配置块 ###################
    ##################
    input_0: "t/target_detector/visualization/overlay"
    input_1: "t/lane_detector/visualization/overlay"
    duplex_0: "s/logic_controller/command"

    # 通用配置块 ###################
    ###########
    fps: 30           # 画面渲染帧率
    port: 8080